import { neon } from '@neondatabase/serverless';
import dotenv from 'dotenv';
dotenv.config({ path: 'server/.env' });
const sql = neon(process.env.DATABASE_URL!);
const rows = await sql`SELECT * FROM users`;
console.log('users', rows);
const consoles = await sql`SELECT * FROM consoles`;
console.log('consoles', consoles.length);
const joueurs = await sql`SELECT * FROM joueurs`;
console.log('joueurs', joueurs.length);
